---
title: Emping
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title"
email: your-email@domain.com
description: 'Let''s Eat!!.

'
baseurl: vaytiennhanh24h.xyz
url: http://example.com
twitter_username: jekyllrb
github_username: jekyll
GoogleAnalytics: UA-xxxxxx-x
twitter:
  username: rmsubekti
facebook:
  app_id: 1234567
  publisher: 1234567
sass:
  style: compressed
markdown: kramdown
kramdown:
  parse_block_html: true
gems:
- jekyll-redirect-from
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jemoji
include:
- _pages
exclude:
- CNAME
- README.md
- Gemfile
- Gemfile.lock
paginate: 12
paginate_path: "/blog/:num"
